{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_failure():\n>       assert False\nE       assert False\n\ntest_allure.py:12: AssertionError"}, "start": 1606189429160, "stop": 1606189429161, "uuid": "1d82e975-6e7a-4f5d-9159-4290c70803f5", "historyId": "b2873979f94e50b7249573af844598f1", "testCaseId": "924c4ecc2b1e866f13aa32d5ad57625b", "fullName": "test_allure#test_failure", "labels": [{"name": "suite", "value": "test_allure"}, {"name": "host", "value": "USER-8VMLUTRGV1"}, {"name": "thread", "value": "15128-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_allure"}]}