{"name": "test_login_fail_a", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1", "trace": "self = <pytest测试框架.test_allure_login.TestLogin object at 0x02F6B530>\n\n    @allure.story(\"用户名缺失\")\n    def test_login_fail_a(self):\n        with allure.step(\"点击用户名\"):\n            print(\"请输入用户名\")\n        with allure.step(\"点击密码\"):\n            print(\"请输入密码\")\n        print(\"点击登录\")\n        with allure.step(\"点击登录之后登录失败\"):\n>           assert '1' ==1\nE           AssertionError: assert '1' == 1\n\ntest_allure_login.py:29: AssertionError"}, "steps": [{"name": "点击用户名", "status": "passed", "start": 1606206277073, "stop": 1606206277074}, {"name": "点击密码", "status": "passed", "start": 1606206277074, "stop": 1606206277074}, {"name": "点击登录之后登录失败", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1\n", "trace": "  File \"D:\\python\\pytest测试框架\\test_allure_login.py\", line 29, in test_login_fail_a\n    assert '1' ==1\n"}, "start": 1606206277074, "stop": 1606206277074}], "attachments": [{"name": "stdout", "source": "9ddf57db-ad73-4baa-9848-97fa5ad021f4-attachment.txt", "type": "text/plain"}], "start": 1606206277073, "stop": 1606206277076, "uuid": "36ee0ed2-d865-4184-9638-157d989b1834", "historyId": "a62121f9a43b51ea8785adafaa03b01d", "testCaseId": "e2b4964c09abbca5ed579766ff1af921", "fullName": "test_allure_login.TestLogin#test_login_fail_a", "labels": [{"name": "feature", "value": "登录模块"}, {"name": "story", "value": "用户名缺失"}, {"name": "suite", "value": "test_allure_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "USER-8VMLUTRGV1"}, {"name": "thread", "value": "17708-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_allure_login"}]}